trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    workingDir: 'frontend'

- task: Npm@1
  displayName: 'Build frontend'
  inputs:
    command: 'run'
    workingDir: 'frontend'
    arguments: 'build'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'myContainerRegistry'
    repository: 'frontend'
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'
    tags: 'latest'
