# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    AzureResourceManagerConnection : test-connection
    subscriptionId: Test-Subscription
    action: 'Create Or Update Resource Group'
    resourceGroupName: :'test-rg'
    location: central-india
    templateLocation: 'Linked artifact'
    csmFile: '/acr-aks-deploy.json'
    csmParametersFile: '/parameter.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    AzureResourceManagerConnection : test-connection
    subscriptionId: Test-Subscription
    action: 'Create Or Update Resource Group'
    resourceGroupName: :'test-rg'
    location: central-india
    templateLocation: 'Linked artifact'
    csmFile: '/postgres-deploy.json'
    csmParametersFile: '/parameter.json'
    deploymentMode: 'Incremental'